apiVersion: v1
kind: Pod
metadata:
 name: myapp-health-probes
spec:
  containers:
  - image: nginx:1.20
    name: myapp-container
    ports:
    - containerPort: 80
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 10   # Tells kubelets that it should wait 10 sec before performing the first probe.
      periodSeconds: 5          # Every 5 seconds.
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 15
      


# kubectl apply -f pod-heath-probes.yaml 
# kubectl get pod
